# Generated by Django 5.0.6 on 2024-05-28 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioTM',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Ingresar correo: ')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre: ')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellido: ')),
                ('direccion', models.CharField(max_length=200, verbose_name='Dirección: ')),
                ('telefono', models.IntegerField(verbose_name='Teléfono: ')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='usuarios', verbose_name='Imagen de perfil: ')),
                ('run', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True, verbose_name='Rut: ')),
                ('es_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
