# Generated by Django 5.0.6 on 2024-05-28 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripción')),
                ('precio', models.IntegerField(verbose_name='Precio')),
                ('stock', models.IntegerField(verbose_name='Stock')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos', verbose_name='Imagen de producto')),
            ],
        ),
        migrations.CreateModel(
            name='Socket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Cpu',
            fields=[
                ('producto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pagina.producto')),
                ('frecuencia', models.FloatField(verbose_name='Frecuencia')),
                ('turbo', models.FloatField(verbose_name='Frecuencia turbo')),
                ('nucleos', models.IntegerField(verbose_name='Núcleos')),
                ('hilos', models.IntegerField(verbose_name='Hilos')),
                ('graficos', models.CharField(max_length=100, verbose_name='Gráficos integrados')),
                ('cache', models.CharField(max_length=100, verbose_name='Caché')),
                ('manufactura', models.CharField(max_length=50, verbose_name='Manufactura')),
                ('tdp', models.IntegerField(verbose_name='TDP')),
                ('nucleo', models.CharField(max_length=50, verbose_name='Núcleo')),
                ('socket_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagina.socket')),
            ],
            bases=('pagina.producto',),
        ),
    ]
