# Generated by Django 5.0.6 on 2024-05-30 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpu',
            name='socket_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pagina.socket', verbose_name='Socket'),
        ),
    ]
